I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/joshroute.rpy", line 47, in script
    Josh "I’m hosting another event about Equality Awareness, and I’m struggling to find for a second host"
Exception: Sayer 'Josh' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/joshroute.rpy", line 47, in script
    Josh "I’m hosting another event about Equality Awareness, and I’m struggling to find for a second host"
  File "C:\Users\Joshua\Desktop\Josh's Stuff\VISUAL NOVELLING\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Joshua\Desktop\Josh's Stuff\VISUAL NOVELLING\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Joshua\Desktop\Josh's Stuff\VISUAL NOVELLING\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Josh' is not defined.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
Paths of Change 1.0
Tue May 27 12:07:01 2025
